In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
data=[
    ['Beef', 'Pork', 'Mutton'],
    ['Pork', 'Mutton', 'Chicken'], 
    ['Mutton', 'Chicken'],
    ['Beef', 'Mutton', 'Chicken'],
    ['Beef', 'Pork', 'Mutton', 'Chicken'],
]

In [4]:
#convert to a format appropriate for apriori
encoder=TransactionEncoder()
encoded=encoder.fit_transform(data)
dataframe=pd.DataFrame(encoded, columns=encoder.columns_)
dataframe

    Beef  Chicken  Mutton   Pork
0   True    False    True   True
1  False     True    True   True
2  False     True    True  False
3   True     True    True  False
4   True     True    True   True

In [5]:
#apply apriori
frequent_items=apriori(dataframe, min_support=0.3, use_colnames=True)
frequent_items

    support                 itemsets
0       0.6                   (Beef)
1       0.8                (Chicken)
2       1.0                 (Mutton)
3       0.6                   (Pork)
4       0.4          (Beef, Chicken)
5       0.6           (Mutton, Beef)
6       0.4             (Beef, Pork)
7       0.8        (Mutton, Chicken)
8       0.4          (Chicken, Pork)
9       0.6           (Mutton, Pork)
10      0.4  (Mutton, Beef, Chicken)
11      0.4     (Mutton, Beef, Pork)
12      0.4  (Mutton, Chicken, Pork)

In [6]:
#create rules
rules=association_rules(frequent_items, min_threshold=0.7, metric='confidence')
rules

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Beef),(Mutton),0.6,1.0,0.6,1.0,1.0,1.0,0.0,inf,0.0,0.6,0.0,0.8
1,(Mutton),(Chicken),1.0,0.8,0.8,0.8,1.0,1.0,0.0,1.0,0.0,0.8,0.0,0.9
2,(Chicken),(Mutton),0.8,1.0,0.8,1.0,1.0,1.0,0.0,inf,0.0,0.8,0.0,0.9
3,(Pork),(Mutton),0.6,1.0,0.6,1.0,1.0,1.0,0.0,inf,0.0,0.6,0.0,0.8
4,"(Beef, Chicken)",(Mutton),0.4,1.0,0.4,1.0,1.0,1.0,0.0,inf,0.0,0.4,0.0,0.7
5,"(Beef, Pork)",(Mutton),0.4,1.0,0.4,1.0,1.0,1.0,0.0,inf,0.0,0.4,0.0,0.7
6,"(Chicken, Pork)",(Mutton),0.4,1.0,0.4,1.0,1.0,1.0,0.0,inf,0.0,0.4,0.0,0.7