In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

In [4]:
data=[
    ['Beef', 'Pork', 'Mutton'],
    ['Pork', 'Mutton', 'Chicken'], 
    ['Mutton', 'Chicken'],
    ['Beef', 'Mutton', 'Chicken'],
    ['Beef', 'Pork', 'Mutton', 'Chicken'],
]

In [5]:
#convert the data into a form suitable for apriori
encoder=TransactionEncoder()
encoded=encoder.fit_transform(data)
dataframe=pd.DataFrame(encoded, columns=encoder.columns_)
dataframe

    Beef  Chicken  Mutton   Pork
0   True    False    True   True
1  False     True    True   True
2  False     True    True  False
3   True     True    True  False
4   True     True    True   True

In [7]:
#apply apriori
frequentitems=apriori(dataframe, min_support=0.4, use_colnames=True)
frequentitems

    support                 itemsets
0       0.6                   (Beef)
1       0.8                (Chicken)
2       1.0                 (Mutton)
3       0.6                   (Pork)
4       0.4          (Chicken, Beef)
5       0.6           (Beef, Mutton)
6       0.4             (Pork, Beef)
7       0.8        (Chicken, Mutton)
8       0.4          (Pork, Chicken)
9       0.6           (Pork, Mutton)
10      0.4  (Chicken, Beef, Mutton)
11      0.4     (Pork, Beef, Mutton)
12      0.4  (Pork, Chicken, Mutton)

In [11]:
#create rules
rules=association_rules(frequentitems, metric="confidence", min_threshold=0.7)
rules

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Beef),(Mutton),0.6,1.0,0.6,1.0,1.0,1.0,0.0,inf,0.0,0.6,0.0,0.8
1,(Chicken),(Mutton),0.8,1.0,0.8,1.0,1.0,1.0,0.0,inf,0.0,0.8,0.0,0.9
2,(Mutton),(Chicken),1.0,0.8,0.8,0.8,1.0,1.0,0.0,1.0,0.0,0.8,0.0,0.9
3,(Pork),(Mutton),0.6,1.0,0.6,1.0,1.0,1.0,0.0,inf,0.0,0.6,0.0,0.8
4,"(Chicken, Beef)",(Mutton),0.4,1.0,0.4,1.0,1.0,1.0,0.0,inf,0.0,0.4,0.0,0.7
5,"(Pork, Beef)",(Mutton),0.4,1.0,0.4,1.0,1.0,1.0,0.0,inf,0.0,0.4,0.0,0.7
6,"(Pork, Chicken)",(Mutton),0.4,1.0,0.4,1.0,1.0,1.0,0.0,inf,0.0,0.4,0.0,0.7