In [18]:
import pandas as pd
supermarket=pd.read_csv('supermarket.csv')
supermarket

    ProductID    ProductName  Quantity  Price     LastUpdated
0           1           Milk        20   65.0  7/5/2025 15:00
1           2          Bread        30   60.0  7/5/2025 14:30
2           3          Sugar        15  120.0  7/4/2025 10:00
3           4          Flour        25  150.0  7/3/2025 16:45
4           5           Rice        40    NaN   7/5/2025 9:15
..        ...            ...       ...    ...             ...
58         56     Cling Film        15   90.0   7/4/2025 9:00
59         57  Aluminum Foil        12  100.0  7/5/2025 12:00
60         58     Trash Bags        25   60.0  7/3/2025 14:45
61         59     Toothpicks        40   30.0  7/4/2025 10:30
62         60   Strawberries         8  250.0  7/5/2025 13:00

[63 rows x 5 columns]

In [19]:
#check for null values
supermarket.isna()

    ProductID  ProductName  Quantity  Price  LastUpdated
0       False        False     False  False        False
1       False        False     False  False        False
2       False        False     False  False        False
3       False        False     False  False        False
4       False        False     False   True        False
..        ...          ...       ...    ...          ...
58      False        False     False  False        False
59      False        False     False  False        False
60      False        False     False  False        False
61      False        False     False  False        False
62      False        False     False  False        False

[63 rows x 5 columns]

In [20]:
#drop null values
supermarket.dropna()

    ProductID         ProductName  Quantity  Price     LastUpdated
0           1                Milk        20   65.0  7/5/2025 15:00
1           2               Bread        30   60.0  7/5/2025 14:30
2           3               Sugar        15  120.0  7/4/2025 10:00
3           4               Flour        25  150.0  7/3/2025 16:45
5           5                Rice        40   80.0   7/5/2025 9:15
6           6         Cooking Oil        18  200.0  7/2/2025 12:00
7           7          Tea Leaves        22   90.0  7/5/2025 11:30
8           8              Coffee        10  250.0   7/4/2025 8:00
10         10               Beans        28  110.0  7/5/2025 13:00
11         11            Soap Bar        50   40.0  7/4/2025 15:10
13         12          Toothpaste        15  120.0   7/3/2025 9:45
15         14        Toilet Paper        60   25.0  7/2/2025 11:30
16         15             Shampoo        12  150.0  7/4/2025 12:15
17         16              Butter         8  200.0   7/5/2025 8:30
18         17             Yoghurt        25   70.0  7/3/2025 13:00
20         18                Eggs        45   15.0  7/5/2025 14:00
21         19                Salt        20   30.0   7/4/2025 9:00
24         22        Water Bottle        50   50.0  7/3/2025 15:00
25         23                Soda        40   60.0  7/4/2025 11:00
26         24            Biscuits        35   45.0   7/5/2025 9:00
27         25              Cereal        18  220.0  7/3/2025 12:00
28         26           Margarine        12  180.0  7/4/2025 14:30
29         27                 Jam        10  150.0  7/5/2025 10:15
30         28       Peanut Butter         8  200.0  7/2/2025 13:45
31         29               Honey         5  300.0   7/4/2025 8:30
32         30          Green Peas        25   80.0  7/5/2025 11:00
33         31             Lentils        20   90.0  7/3/2025 10:30
34         32       Chapati Flour        30  140.0  7/4/2025 12:00
35         33       Baking Powder        15   50.0  7/5/2025 13:30
36         34               Yeast        10   60.0   7/3/2025 9:15
37         35        Cocoa Powder         8  180.0  7/4/2025 15:45
38         36        Tomato Paste        20   70.0   7/5/2025 8:00
39         37           Soy Sauce        12  100.0  7/2/2025 11:00
40         38          Spices Mix        25   80.0  7/4/2025 10:45
41         39       Bar Chocolate        30   90.0  7/5/2025 12:15
42         40        Canned Beans        18  100.0  7/3/2025 14:00
43         41         Canned Corn        15  110.0   7/4/2025 9:30
44         42             Diapers        40   25.0  7/5/2025 11:45
45         43           Baby Food        10  200.0  7/3/2025 13:15
46         44      Hand Sanitizer        20  120.0   7/4/2025 8:00
47         45          Face Masks        50   10.0  7/5/2025 10:00
48         46        Laundry Soap        30   50.0  7/2/2025 12:30
49         47  Dishwashing Liquid        15   90.0  7/4/2025 14:00
50         48       Air Freshener        12  150.0   7/5/2025 9:45
51         49    Insect Repellent        10  180.0  7/3/2025 11:30
52         50         Light Bulbs        20  100.0  7/4/2025 12:45
53         51           Batteries        25   80.0   7/5/2025 8:15
54         52             Matches        60    5.0  7/3/2025 10:00
55         53             Candles        30   20.0  7/4/2025 13:00
56         54        Plastic Bags        50   10.0  7/5/2025 11:15
57         55        Paper Towels        20   70.0  7/3/2025 15:30
58         56          Cling Film        15   90.0   7/4/2025 9:00
59         57       Aluminum Foil        12  100.0  7/5/2025 12:00
60         58          Trash Bags        25   60.0  7/3/2025 14:45
61         59          Toothpicks        40   30.0  7/4/2025 10:30
62         60        Strawberries         8  250.0  7/5/2025 13:00

In [22]:
#check for duplicates
supermarket.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
58    False
59    False
60    False
61    False
62    False
Length: 63, dtype: bool

In [23]:
supermarket.drop_duplicates()

    ProductID    ProductName  Quantity  Price     LastUpdated
0           1           Milk        20   65.0  7/5/2025 15:00
1           2          Bread        30   60.0  7/5/2025 14:30
2           3          Sugar        15  120.0  7/4/2025 10:00
3           4          Flour        25  150.0  7/3/2025 16:45
4           5           Rice        40    NaN   7/5/2025 9:15
..        ...            ...       ...    ...             ...
58         56     Cling Film        15   90.0   7/4/2025 9:00
59         57  Aluminum Foil        12  100.0  7/5/2025 12:00
60         58     Trash Bags        25   60.0  7/3/2025 14:45
61         59     Toothpicks        40   30.0  7/4/2025 10:30
62         60   Strawberries         8  250.0  7/5/2025 13:00

[63 rows x 5 columns]

In [32]:
#normalize Quantity and Price
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
supermarket[['Quantity','Price']]=scaler.fit_transform(supermarket[['Quantity','Price']])
supermarket.head()

   ProductID ProductName  Quantity     Price     LastUpdated
0          1        Milk  0.272727  0.203390  7/5/2025 15:00
1          2       Bread  0.454545  0.186441  7/5/2025 14:30
2          3       Sugar  0.181818  0.389831  7/4/2025 10:00
3          4       Flour  0.363636  0.491525  7/3/2025 16:45
4          5        Rice  0.636364       NaN   7/5/2025 9:15

In [37]:
#Starndadization
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
supermarket[['Quantity','Price']]=scaler.fit_transform(supermarket[['Quantity','Price']])
supermarket

    ProductID    ProductName  Quantity     Price     LastUpdated
0           1           Milk -0.335988 -0.560878  7/5/2025 15:00
1           2          Bread  0.391409 -0.634608  7/5/2025 14:30
2           3          Sugar -0.699687  0.250157  7/4/2025 10:00
3           4          Flour  0.027710  0.692539  7/3/2025 16:45
4           5           Rice  1.118806       NaN   7/5/2025 9:15
..        ...            ...       ...       ...             ...
58         56     Cling Film -0.699687 -0.192226   7/4/2025 9:00
59         57  Aluminum Foil -0.917906 -0.044765  7/5/2025 12:00
60         58     Trash Bags  0.027710 -0.634608  7/3/2025 14:45
61         59     Toothpicks  1.118806 -1.076991  7/4/2025 10:30
62         60   Strawberries -1.208865  2.167148  7/5/2025 13:00

[63 rows x 5 columns]